services:
  firewallenvironment:
    container_name: firewallenvironment
    env_file:
      - ./api/.env.docker
    build:
      context: .
    ports:
    - "${SERVER_PORT}:${SERVER_PORT}"
    depends_on:
      - postgres
  
  sigma-redis:
    image: redis:7.2-alpine
    env_file:
      - ./api/.env.docker
    container_name: sigma-redis
    ports:
      - "${REDIS_PORT}:${REDIS_PORT}"
    volumes:
      - ./docker/redis-data:/data
    command: ["redis-server", "--save", "60", "1", "--loglevel", "warning", "--maxmemory", "512mb"]
    environment:
      - REDIS_MAXMEMORY=512mb
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3

  postgres:
    image: postgres:17
    env_file:
      - ./api/.env.docker
    restart: "always"
    environment:
      TZ: "America/Sao_Paulo"
      PGTZ: "America/Sao_Paulo"
    ports:
      - "${POSTGRES_PORT}:${POSTGRES_PORT}"
    volumes:
      - ./docker/postgres/data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 10

  grafana:
    image: grafana/grafana-oss:10.0.12
    restart: "always"
    user: "root"
    environment:
      GF_INSTALL_PLUGINS: "grafana-clock-panel, grafana-simple-json-datasource"
      GF_PANELS_ENABLE_ALPHA: true
    ports:
      - "3000:3000"
    volumes:
      - ./docker/grafana:/var/lib/grafana
    logging:
      driver: "none"


networks:
  default:
    driver: bridge
