version: '3.1'

services:
  postgres:
    image: postgres:17
    restart: "always"
    ports:
      - "5433:5432"
    volumes:
      - ./postgres/data:/var/lib/postgresql/data
      - ./init-db:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: Q1w2e3r4
      POSTGRES_DB: firewall

  grafana:
    image: grafana/grafana-oss:10.0.12
    restart: "always"
    environment:
      GF_INSTALL_PLUGINS: "grafana-clock-panel, grafana-simple-json-datasource"
      GF_PANELS_ENABLE_ALPHA: true
    ports:
      - "3000:3000"
    volumes:
      - ./grafana:/var/lib/grafana

networks:
  default:
    driver: bridge
