# Generated by Django 5.1.2 on 2024-10-25 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netcontrol', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bl_address_local',
            name='timestamp_added',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='bl_local_cache',
            name='timestamp_added',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
