# Generated by Django 5.1.2 on 2024-11-05 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('netcontrol', '0003_wladdresslocal_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='tarpitaddresslocal',
            table='tp_address_local',
        ),
        migrations.AlterModelTable(
            name='wladdresslocal',
            table='wl_address_local',
        ),
    ]
