# Generated by Django 5.1.2 on 2024-11-09 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('netcontrol', '0004_alter_tarpitaddresslocal_table_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BlAddressLocal',
            new_name='Blacklist',
        ),
        migrations.RenameModel(
            old_name='TarpitAddressLocal',
            new_name='Tarpit',
        ),
        migrations.RenameModel(
            old_name='WlAddressLocal',
            new_name='Whitelist',
        ),
        migrations.DeleteModel(
            name='BlLocalCache',
        ),
        migrations.DeleteModel(
            name='NetworkTraffic',
        ),
        migrations.AlterModelTable(
            name='blacklist',
            table='blacklist',
        ),
        migrations.AlterModelTable(
            name='tarpit',
            table='tarpit',
        ),
        migrations.AlterModelTable(
            name='whitelist',
            table='whitelist',
        ),
    ]
