# Generated by Django 5.1.2 on 2025-03-31 18:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('netcontrol', '0014_rename_abuse_confidence_score_blacklist_abuseipdb_confidence_score_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blacklist',
            old_name='ip',
            new_name='ip_address',
        ),
        migrations.RenameField(
            model_name='suspect',
            old_name='ip',
            new_name='ip_address',
        ),
        migrations.RenameField(
            model_name='tarpit',
            old_name='ip',
            new_name='ip_address',
        ),
        migrations.RenameField(
            model_name='whitelist',
            old_name='ip',
            new_name='ip_address',
        ),
    ]
