# Generated by Django 5.1.2 on 2024-11-04 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netcontrol', '0002_alter_bl_address_local_timestamp_added_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WlAddressLocal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.CharField(max_length=45, unique=True)),
                ('country_code', models.CharField(max_length=3, null=True)),
                ('abuse_confidence_score', models.IntegerField(null=True)),
                ('last_reported_at', models.DateTimeField(blank=True, null=True)),
                ('src_longitude', models.FloatField(null=True)),
                ('src_latitude', models.FloatField(null=True)),
                ('timestamp_added', models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                'db_table': 'wl_addres_local',
            },
        ),
        migrations.RenameModel(
            old_name='bl_address_local',
            new_name='BlAddressLocal',
        ),
        migrations.RenameModel(
            old_name='bl_local_cache',
            new_name='BlLocalCache',
        ),
        migrations.RenameModel(
            old_name='network_traffic',
            new_name='NetworkTraffic',
        ),
        migrations.RenameModel(
            old_name='tp_address_local',
            new_name='TarpitAddressLocal',
        ),
        migrations.DeleteModel(
            name='wl_address_local',
        ),
        migrations.AlterModelTable(
            name='bladdresslocal',
            table='bl_address_local',
        ),
        migrations.AlterModelTable(
            name='bllocalcache',
            table='bl_local_cache',
        ),
        migrations.AlterModelTable(
            name='networktraffic',
            table='network_traffic',
        ),
        migrations.AlterModelTable(
            name='tarpitaddresslocal',
            table='tp_addres_local',
        ),
    ]
