# Generated by Django 5.1.2 on 2024-11-11 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netcontrol', '0005_rename_bladdresslocal_blacklist_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarpit',
            name='city',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='whitelist',
            name='city',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
