# Generated by Django 5.1.2 on 2024-11-14 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netcontrol', '0006_tarpit_city_whitelist_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarpit',
            name='timestamp_added',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
