# Generated by Django 5.1.2 on 2024-11-18 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netcontrol', '0007_tarpit_timestamp_added'),
    ]

    operations = [
        migrations.AddField(
            model_name='blacklist',
            name='num_distinct_users',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='blacklist',
            name='total_reports',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='tarpit',
            name='num_distinct_users',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='tarpit',
            name='total_reports',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='whitelist',
            name='num_distinct_users',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='whitelist',
            name='total_reports',
            field=models.FloatField(null=True),
        ),
    ]
