# Generated by Django 5.1.2 on 2024-11-25 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netcontrol', '0008_blacklist_num_distinct_users_blacklist_total_reports_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='whitelist',
            name='harmless_virustotal',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='whitelist',
            name='malicious_virustotal',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='whitelist',
            name='suspicious_virustotal',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='whitelist',
            name='undetected_virustotal',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='whitelist',
            name='virustotal_reputation',
            field=models.IntegerField(null=True),
        ),
    ]
