# Generated by Django 5.1.2 on 2025-01-08 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netcontrol', '0011_tarpit_harmless_virustotal_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='blacklist',
            name='ipvoid_detection_count',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='blacklist',
            name='risk_recommended_pulsedive',
            field=models.CharField(max_length=45, null=True),
        ),
        migrations.AddField(
            model_name='tarpit',
            name='ipvoid_detection_count',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='tarpit',
            name='risk_recommended_pulsedive',
            field=models.CharField(max_length=45, null=True),
        ),
        migrations.AddField(
            model_name='whitelist',
            name='ipvoid_detection_count',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='whitelist',
            name='risk_recommended_pulsedive',
            field=models.CharField(max_length=45, null=True),
        ),
    ]
