# Generated by Django 5.1.2 on 2025-03-27 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netcontrol', '0012_blacklist_ipvoid_detection_count_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Suspect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.CharField(max_length=45, unique=True)),
                ('country_code', models.CharField(max_length=3, null=True)),
                ('city', models.CharField(max_length=255, null=True)),
                ('abuse_confidence_score', models.IntegerField(null=True)),
                ('total_reports', models.FloatField(null=True)),
                ('num_distinct_users', models.FloatField(null=True)),
                ('virustotal_reputation', models.IntegerField(null=True)),
                ('harmless_virustotal', models.IntegerField(null=True)),
                ('malicious_virustotal', models.IntegerField(null=True)),
                ('suspicious_virustotal', models.IntegerField(null=True)),
                ('undetected_virustotal', models.IntegerField(null=True)),
                ('ipvoid_detection_count', models.IntegerField(null=True)),
                ('risk_recommended_pulsedive', models.CharField(max_length=45, null=True)),
                ('last_reported_at', models.DateTimeField(blank=True, null=True)),
                ('timestamp_added', models.DateTimeField(auto_now_add=True, null=True)),
                ('src_latitude', models.FloatField(null=True)),
                ('src_longitude', models.FloatField(null=True)),
            ],
            options={
                'db_table': 'suspect',
            },
        ),
    ]
