# Generated by Django 5.1.2 on 2025-08-26 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('netcontrol', '0015_rename_ip_blacklist_ip_address_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Tarpit',
            new_name='Analysis',
        ),
        migrations.AlterModelTable(
            name='analysis',
            table='analysis',
        ),
    ]
